{
    'name': 'VIT Demo POS',
    'version': '17.0.1.0.0',
    'category': 'Point of Sale',
    'summary': """Belong to VIT""",
    'author': 'Visi Intech',
    'company': 'Visi Intech',
    'maintainer': 'Visi Intech',
    'website': "https://www.Visi-Intech.com",
    'depends': ['point_of_sale', 'contacts', 'base', 'web', 'account', 'sale', 'stock'],
    'data': [
        # 'security/hr_security.xml',
        'security/ir.model.access.csv',
        'views/views_pos_order.xml',
        'views/views_stock_picking.xml',
        'views/views_res_partner.xml',
        'views/views_account_move.xml',
        'views/views_account_payment.xml',
        'views/views_log_code_runtime.xml',
        'views/views_log_note.xml',
        'views/menu_log_note.xml',
        'views/views_pos_session.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}