from . import pos_order
from . import stock_picking
from . import account_move
from . import account_payment
from . import res_partner
from . import log_code_runtime
from . import log_note
from . import pos_session
from . import pos_order_line
from . import ir_sequence
from . import stock_picking_type
from . import product_template